#!/usr/bin/env ansible-playbook
---
- name: run cmd in containers
  hosts: docker
  gather_facts: no
  strategy: free  # free|linear
  serial: 10
  vars:
    package: vim  # placeholder package
    cmd:  "{{pkgmgr}} -y -q update && {{pkgmgr}} -y -q install {{package}}"
  tasks:

    - debug: var=cmd

    - name: start containers
      docker_container:
        name: "{{inventory_hostname}}"
        image: "{{docker_image}}"
        command: /bin/bash -c "{{cmd}}"
        detach: no
        privileged: yes
